name: workflowfirst
on: push

jobs:
 First-Job:
    runs-on: ubuntu-latest
    steps:
       - name: step1
         uses: actions/checkout@v2
       - name: step2
         run: date "+%H:%M:%S   %d/%m/%y"

 Second-Job:
    runs-on: windows-latest
    steps:
       - name: step1
         uses: actions/checkout@v2
       - name: step2
         run: echo %date:~-4%%date:~3,2%%date:~0,2%%time:~0,2%%time:~3,2%%time:~6,2%

 third-Job:
    runs-on: macos-latest
    steps:
       - name: step1
         uses: actions/checkout@v2
       - name: step2
         run: date +%F
 fourth-name:
     runs-on: macos-latest
     needs: [First-Job, Second-Job, third-Job]
     steps:
       - name: step1
         uses: actions/checkout@v2
       - name: step2
         run: now=$(date)




